"""
06_inspect_artifacts.py — MLOps Artifact Viewer
Fetches the latest pipeline run and previews the stored payloads and metrics 
for each of the four artifact stages (Bronze, Silver, Gold, Aggregates).
"""

import os
import json
from dotenv import load_dotenv
from pymongo import MongoClient

# Load environment variables
load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")
DB_NAME = os.getenv("MONGO_DB_NAME", "travel_pipeline_db")
ARTIFACTS_COLLECTION = "pipeline_artifacts"

# The four artifact types generated by your pipeline
ARTIFACT_TYPES = [
    "raw_ingestion",           # Step 1
    "processed_scraped_docs",  # Step 2
    "sentiment_scores",        # Step 3
    "feature_aggregates"       # Step 4
]

def inspect_artifacts():
    if not MONGO_URI:
        print("❌ Error: MONGO_URI is missing. Cannot connect to MongoDB.")
        return

    print(f"🔌 Connecting to MongoDB: {DB_NAME}...\n")
    client = MongoClient(MONGO_URI)
    db = client[DB_NAME]

    # 1. Find the most recent run_id
    latest_artifact = db[ARTIFACTS_COLLECTION].find_one(sort=[("timestamp", -1)])
    
    if not latest_artifact:
        print("❌ No artifacts found in the database. Have you run the pipeline yet?")
        client.close()
        return

    latest_run_id = latest_artifact.get("run_id")
    print("="*80)
    print(f"🔎 INSPECTING LATEST PIPELINE RUN: {latest_run_id}")
    print("="*80)

    # 2. Fetch and display each artifact type for this run_id
    for a_type in ARTIFACT_TYPES:
        print(f"\n📦 ARTIFACT TYPE: {a_type.upper()}")
        print("-" * 80)
        
        artifact = db[ARTIFACTS_COLLECTION].find_one({
            "run_id": latest_run_id,
            "artifact_type": a_type
        })

        if not artifact:
            print(f"⚠️  No artifact found for '{a_type}' in this run.")
            continue

        # Extract basic info
        doc_count = artifact.get("document_count", "N/A")
        metrics = artifact.get("metrics", {})
        payload = artifact.get("payload", [])

        print(f"Total Documents : {doc_count}")
        
        # Print metrics if they exist (Steps 2, 3, and 4 use metrics)
        if metrics:
            print("Metrics         :")
            print(json.dumps(metrics, indent=4))

        # Preview the first item in the payload to see the schema
        print("\nPayload Preview (First Item):")
        if payload and isinstance(payload, list) and len(payload) > 0:
            first_item = payload[0]
            
            # Truncate long text fields for the console output so it doesn't flood the screen
            preview_item = first_item.copy()
            for key in ["text", "description", "content"]:
                if key in preview_item and isinstance(preview_item[key], str) and len(preview_item[key]) > 100:
                    preview_item[key] = preview_item[key][:100] + "... [TRUNCATED FOR PREVIEW]"
                    
            print(json.dumps(preview_item, indent=4))
        else:
            print("  [Payload is empty or not a list]")
            
        print("=" * 80)

    client.close()
    print("\n✅ Inspection Complete.")

if __name__ == "__main__":
    inspect_artifacts()